### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by chivasblue** [ohmu/pgmemcache#36]
The make command is failing with below error on Ubuntu 14.04

---

postgres@ubuntu:~/pgmemcache$ make
gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC -pie -I/usr/include/mit-krb5 -DLINUX_OOM_SCORE_ADJ=0 -fno-omit-frame-pointer -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -fpic -I. -I./ -I/usr/include/postgresql/9.3/server -I/usr/include/postgresql/internal -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.6  -c -o pgmemcache.o pgmemcache.c
In file included from pgmemcache.c:11:0:
pgmemcache.h:26:31: fatal error: libmemcached/sasl.h: No such file or directory
 #include <libmemcached/sasl.h>
                               ^
compilation terminated.
make: **\* [pgmemcache.o] Error 1

postgres@ubuntu:~$ locate sasl.h
/usr/local/include/libmemcached-1.0/sasl.h
/usr/local/include/libmemcached-1.0/struct/sasl.h
/var/lib/postgresql/libmemcached-1.0.18/libmemcached/sasl.hpp
/var/lib/postgresql/libmemcached-1.0.18/libmemcached-1.0/sasl.h
/var/lib/postgresql/libmemcached-1.0.18/libmemcached-1.0/struct/sasl.h

---

Can you let me know how to point correctly to libmemcached/sasl.h during make process?

Thanks!

**Comment by Fawaz-Mohammed** [comment]
Make sure that you have installed the needed library before building the package:
$sudo apt-get install libmemcached6-dev  libsasl2-dev
