### ISSUE TITLE
Delete/Remove Dead server 

### ISSUE THREAD

**Issue by chivasblue** [ohmu/pgmemcache#38]
Hi, 

My scenario is as below:
Running 2 memcached servers

select memcache_stats();
        memcache_stats        
------------------------------
                             +
 Server: 192.168.1.33 (11211)+
 pid: 2061                   +
 uptime: 4                   +
 time: 1426227684            +
 version: 1.4.14             +
 pointer_size: 64            +
 rusage_user: 0.2712         +
 rusage_system: 0.4045       +
 curr_items: 0               +
 total_items: 0              +
 bytes: 0                    +
 curr_connections: 5         +
 total_connections: 6        +
 connection_structures: 6    +
 cmd_get: 0                  +
 cmd_set: 0                  +
 get_hits: 0                 +
 get_misses: 0               +
 evictions: 0                +
 bytes_read: 8               +
 bytes_written: 0            +
 limit_maxbytes: 536870912   +
 threads: 4                  +
 Server: 192.168.1.35 (11211)+
 pid: 1385                   +
 uptime: 7                   +
 time: 1426227685            +
 version: 1.4.14             +
 pointer_size: 64            +
 rusage_user: 0.1417         +
 rusage_system: 0.1780       +
 curr_items: 0               +
 total_items: 0              +
 bytes: 0                    +
 curr_connections: 5         +
 total_connections: 6        +
 connection_structures: 6    +
 cmd_get: 0                  +
 cmd_set: 0                  +
 get_hits: 0                 +
 get_misses: 0               +
 evictions: 0                +
 bytes_read: 8               +
 bytes_written: 0            +
 limit_maxbytes: 536870912   +
 threads: 4  

select memcache_set(id,a||','||b||','||c||','||d) from mydb.test;
 memcache_set 
--------------
 t
 t
 t
 t
 t

1 memcache server goes down

select memcache_set(id,a||','||b||','||c||','||d) from mydb.test;
WARNING:  SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY
WARNING:  SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY
WARNING:  SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY
WARNING:  SERVER HAS FAILED AND IS DISABLED UNTIL TIMED RETRY
 memcache_set 
--------------
 f
 t
 f
 f
 f

I keep getting this error, how do I delete the server which went down from pgmemcache configuration.
I have used pgmemcache.default_servers in conf file to add the servers at startup. I tried using pgmemcache.default_behavior = 'DEAD_TIMEOUT:2', but seems like this parameter is not supported as it gives an error during postgres startup.
The environment is Postgres 9.3 running on Ubuntu 14.04

Thanks!

**Comment by saaros** [comment]
You did not mention which version of pgmemcache you use, pgmemcache 2.2.0 and newer support DEAD_TIMEOUT.  pgmemcache doesn't make any decisions about servers to use, it just passes the list of them and the set of behaviors to libmemcached (or omcache) which uses them.

Note that libmemcached state is not saved or shared accross sessions so libmemcached starts from "scratch" for every pg connection.  This means that if you open a new PG session for each client request you'll always end up accessing all servers before libmemcached decides to mark them dead.

**Comment by saaros** [comment]
Closing this ticket as it looks like there's no need for changes in pgmemcache.
