### ISSUE TITLE
memcache_stats() crash the system

### ISSUE THREAD

**Issue by aliouiiii** [ohmu/pgmemcache#41]
ON PG 9.5:
CREATE EXTENSION pgmemcache WITH SCHEMA pgmemcache;
select pgmemcache.memcache_server_add('localhost');
select pgmemcache.memcache_stat();

crush database ;
error message from db log 
 >LOG:  server process (PID 2265) was terminated by signal 11: Segmentation fault
 >DETAIL:  Failed process was running: select * from pgmemcache.memcache_stats ();
 >LOG:  terminating any other active server processes

not just memcache_stat function
when i used just two function memcache_set and memcache_get_multi after a while it crush the system with error saying : 
*** Error in `postgres: user_name db_name client_ip(41613) SELECT': double free or corruption (!prev): 0x000000000182bcb0 *** 
======= Backtrace: ========= ???

**Comment by saaros** [comment]
Which pgmemcache and libmemcached versions are you using?  libmemcached had a bunch of bugs with regard to using the memory allocation functions provided to it by pgmemcache.  We removed custom memory allocation functions in pgmemcache 2.2.0.

**Comment by aliouiiiii** [comment]
from postgresql repo for redhat/centos/... os:
latest version of pgmemcache is 2.1.2
and for libmemcached is 1.0.16

**Comment by saaros** [comment]
Those are old versions known to have issues, see cb06b448c534ac99ddd08f264e6f86162ddd6b72.  The packages in yum.postgresql.org need to be upgraded.

**Comment by aliouiiiii** [comment]
ok thanks
i think you can  close this issue

**Comment by saaros** [comment]
http://www.postgresql.org/message-id/5715C30F.70408@aiven.io
